/*
 * rss_daemon.c — Raptor Streaming System daemonization and signal handling
 *
 * Standard double-fork daemonization, PID file management,
 * and POSIX signal setup for clean shutdown / config reload.
 */

#include "rss_common.h"

/* Build info — generated by raptor Makefile into rss_build.h */
#ifdef __has_include
#if __has_include("rss_build.h")
#include "rss_build.h"
#endif
#endif
#ifndef RSS_BUILD_HASH
#define RSS_BUILD_HASH "unknown"
#endif
#ifndef RSS_BUILD_TIME
#define RSS_BUILD_TIME "unknown"
#endif

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>
#include <fcntl.h>
#include <getopt.h>
#include <sys/stat.h>
#include <errno.h>

#define PID_DIR "/var/run/rss"
#define PID_PATH_MAX 128

/* ------------------------------------------------------------------ */
/* Signal state                                                        */
/* ------------------------------------------------------------------ */

static volatile sig_atomic_t g_running = 1;
static volatile sig_atomic_t g_reload = 0;

static void sig_term_handler(int sig)
{
    (void)sig;
    g_running = 0;
}

static void sig_hup_handler(int sig)
{
    (void)sig;
    g_reload = 1;
}

/* ------------------------------------------------------------------ */
/* PID file helpers                                                    */
/* ------------------------------------------------------------------ */

static void make_pid_path(char *buf, int buf_size, const char *name)
{
    snprintf(buf, (size_t)buf_size, "%s/%s.pid", PID_DIR, name);
}

static int write_pid_file(const char *name)
{
    char path[PID_PATH_MAX];
    make_pid_path(path, (int)sizeof(path), name);

    rss_mkdir_p(PID_DIR);

    /* Use raw I/O — stdio fopen/fprintf internally malloc buffers
     * which can interfere with subsequent mmap on MIPS uclibc */
    int fd = open(path, O_WRONLY | O_CREAT | O_TRUNC, 0600);
    if (fd < 0)
        return -1;
    char buf[16];
    int len = snprintf(buf, sizeof(buf), "%d\n", (int)getpid());
    write(fd, buf, (size_t)len);
    close(fd);
    return 0;
}

/* ------------------------------------------------------------------ */
/* Daemonization                                                       */
/* ------------------------------------------------------------------ */

int rss_daemonize(const char *name, bool already_daemon)
{
    /* Reject if another instance is already running */
    int existing = rss_daemon_check(name);
    if (existing > 0) {
        fprintf(stderr, "%s: already running (pid %d)\n", name, existing);
        return -1;
    }

    if (!already_daemon) {
        /* First fork — detach from parent */
        pid_t pid = fork();
        if (pid < 0)
            return -1;
        if (pid > 0)
            _exit(0); /* parent exits */

        /* New session leader */
        if (setsid() < 0)
            return -1;

        /* Second fork — prevent reacquiring a controlling terminal */
        pid = fork();
        if (pid < 0)
            return -1;
        if (pid > 0)
            _exit(0);

        /* Redirect stdin/stdout/stderr to /dev/null */
        int fd = open("/dev/null", O_RDWR);
        if (fd >= 0) {
            dup2(fd, STDIN_FILENO);
            dup2(fd, STDOUT_FILENO);
            dup2(fd, STDERR_FILENO);
            if (fd > STDERR_FILENO)
                close(fd);
        }

        chdir("/");
        umask(0);
    }

    return write_pid_file(name);
}

void rss_daemon_cleanup(const char *name)
{
    char path[PID_PATH_MAX];
    make_pid_path(path, (int)sizeof(path), name);
    unlink(path);
}

int rss_daemon_check(const char *name)
{
    char path[PID_PATH_MAX];
    make_pid_path(path, (int)sizeof(path), name);

    FILE *fp = fopen(path, "r");
    if (!fp)
        return 0;

    int pid = 0;
    if (fscanf(fp, "%d", &pid) != 1 || pid <= 0) {
        fclose(fp);
        return 0;
    }
    fclose(fp);

    /* Check if process is alive */
    if (kill((pid_t)pid, 0) == 0)
        return pid;

    if (errno == EPERM)
        return pid; /* exists but we lack permission to signal it */

    /* Stale PID file */
    return 0;
}

/* ------------------------------------------------------------------ */
/* Signal handling                                                     */
/* ------------------------------------------------------------------ */

volatile sig_atomic_t *rss_signal_init(void)
{
    struct sigaction sa;

    g_running = 1;
    g_reload = 0;

    /* SIGTERM, SIGINT → clean shutdown */
    memset(&sa, 0, sizeof(sa));
    sa.sa_handler = sig_term_handler;
    sigemptyset(&sa.sa_mask);
    sa.sa_flags = 0;
    sigaction(SIGTERM, &sa, NULL);
    sigaction(SIGINT, &sa, NULL);

    /* SIGHUP → config reload */
    memset(&sa, 0, sizeof(sa));
    sa.sa_handler = sig_hup_handler;
    sigemptyset(&sa.sa_mask);
    sa.sa_flags = 0;
    sigaction(SIGHUP, &sa, NULL);

    /* SIGPIPE → ignore (broken socket writes) */
    memset(&sa, 0, sizeof(sa));
    sa.sa_handler = SIG_IGN;
    sigemptyset(&sa.sa_mask);
    sa.sa_flags = 0;
    sigaction(SIGPIPE, &sa, NULL);

    return &g_running;
}

bool rss_signal_reload_requested(void)
{
    if (g_reload) {
        g_reload = 0;
        return true;
    }
    return false;
}

/* ------------------------------------------------------------------ */
/* Daemon init helper                                                  */
/* ------------------------------------------------------------------ */

int rss_daemon_init(rss_daemon_ctx_t *ctx, const char *name, int argc, char **argv)
{
    if (!ctx || !name)
        return -1;

    memset(ctx, 0, sizeof(*ctx));
    ctx->name = name;

    const char *config_path = "/etc/raptor.conf";
    bool foreground = false;
    bool debug = false;
    int opt;

    optind = 1; /* reset getopt */
    while ((opt = getopt(argc, argv, "c:fdh")) != -1) {
        switch (opt) {
        case 'c':
            config_path = optarg;
            break;
        case 'f':
            foreground = true;
            break;
        case 'd':
            debug = true;
            break;
        case 'h':
            fprintf(stderr, "Usage: %s [-c config] [-f] [-d] [-h]\n"
                            "  -c <file>   Config file (default: /etc/raptor.conf)\n"
                            "  -f          Run in foreground\n"
                            "  -d          Debug logging\n"
                            "  -h          Show this help\n",
                    name);
            return 1; /* clean exit */
        default:
            return -1;
        }
    }

    ctx->config_path = config_path;
    ctx->foreground = foreground;
    ctx->debug = debug;

    /* Initial logging to stderr/syslog so config load errors are visible */
    rss_log_init(name, debug ? RSS_LOG_DEBUG : RSS_LOG_INFO,
                 foreground ? RSS_LOG_TARGET_STDERR : RSS_LOG_TARGET_SYSLOG, NULL);

    ctx->cfg = rss_config_load(config_path);
    if (!ctx->cfg) {
        RSS_FATAL("failed to load config: %s", config_path);
        return -1;
    }

    /* Re-init logging from [log] config section.
     * -d flag overrides config level. -f overrides target to stderr. */
    {
        const char *cfg_level = rss_config_get_str(ctx->cfg, "log", "level", "info");
        const char *cfg_target = rss_config_get_str(ctx->cfg, "log", "target", "syslog");
        const char *cfg_file = rss_config_get_str(ctx->cfg, "log", "file", "");

        rss_log_level_t level = RSS_LOG_INFO;
        if (strcmp(cfg_level, "fatal") == 0) level = RSS_LOG_FATAL;
        else if (strcmp(cfg_level, "error") == 0) level = RSS_LOG_ERROR;
        else if (strcmp(cfg_level, "warn") == 0) level = RSS_LOG_WARN;
        else if (strcmp(cfg_level, "info") == 0) level = RSS_LOG_INFO;
        else if (strcmp(cfg_level, "debug") == 0) level = RSS_LOG_DEBUG;
        else if (strcmp(cfg_level, "trace") == 0) level = RSS_LOG_TRACE;
        if (debug) level = RSS_LOG_DEBUG; /* -d flag overrides */

        rss_log_target_t target = RSS_LOG_TARGET_SYSLOG;
        if (foreground) target = RSS_LOG_TARGET_STDERR; /* -f overrides */
        else if (strcmp(cfg_target, "stderr") == 0) target = RSS_LOG_TARGET_STDERR;
        else if (strcmp(cfg_target, "file") == 0) target = RSS_LOG_TARGET_FILE;

        rss_log_init(name, level, target, cfg_file[0] ? cfg_file : NULL);
    }

    if (rss_daemonize(name, foreground) < 0) {
        RSS_FATAL("daemonize failed");
        rss_config_free(ctx->cfg);
        ctx->cfg = NULL;
        return -1;
    }

    ctx->running = rss_signal_init();
    RSS_INFO("Raptor Streaming System — %s [%s] built %s", name, RSS_BUILD_HASH, RSS_BUILD_TIME);
    return 0;
}
